<a href="https://colab.research.google.com/github/minerva12938/ai_notes_s22/blob/main/day_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
'''
numpy
- functions
- operations

reasons to use:
- structure
- easy to use
- manage data
- array functions are faster in numpy than normal python

data
- information
'''

'\nnumpy\n- functions\n- operations\n\nreasons to use:\n- structure\n- easy to use\n- manage data\n\ndata\n- information\n'

In [3]:
import numpy as np

In [4]:
lt = [1, 2, 3, 4]
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [8]:
b = np.array([0.5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])
#gets every 20th element
b[::20]
#gets every other element
print(b[::2])

[ 0.5  3.   5.   7.   9.  11.  13. ]


In [10]:
#array[start, end, step_size]
#reverses it
b[::-1]
#gets every other element from the end
b[::-2]

array([13. , 11. ,  9. ,  7. ,  5. ,  3. ,  0.5])

In [23]:
print(b[3:10:-2])

print(b[3::-1])
print(b[:10:-1])

print(b[3:10:-1])

print(b[10:3])
print(b[10:3:-2])
print(b[10:3:-1])


[]
[4.  3.  2.  0.5]
[13. 12.]
[]
[]
[11.  9.  7.  5.]
[11. 10.  9.  8.  7.  6.  5.]


In [25]:
#meeting password: 1970
np.ones(4)

array([1., 1., 1., 1.])

In [27]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.empty(4)

array([1., 1., 1., 1.])

In [35]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [38]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
import random
np.random.rand(5)

array([0.42641719, 0.85721397, 0.26060571, 0.40114845, 0.26522164])

In [50]:
# np.random.rand(height, width)

In [51]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
#6 rows and 2 columns; doesn't work if the array isn't 12
#doesn't work if you have too many or not enough
a.reshape(6, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [53]:
a.max()

12

In [60]:
#1st #: range - [#, #), 2nd is dimensions of 2D array
np.random.randint(10, 23, size = (3,4))

array([[12, 13, 21, 12],
       [18, 20, 12, 18],
       [13, 18, 17, 22]])

In [67]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

In [68]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [69]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
#faster than normal pythong function
np.concatenate((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11])

In [74]:
#adds entire list to a as one element
a = [1, 2, 3, 4, 5]
b = [4, 5, 6, 7, 8]
a.append(b)

In [75]:
a

[1, 2, 3, 4, 5, [4, 5, 6, 7, 8]]

In [77]:
#makes the list continuous, where b is added 
#to the end as by each element, not the whole thing
#at once
a = [1, 2, 3, 4, 5]
b = [4, 5, 6, 7, 8]
a.extend(b)

In [78]:
a

[1, 2, 3, 4, 5, 4, 5, 6, 7, 8]

In [83]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [85]:
arr.shape

(3, 3)

In [87]:
arr.size

9

In [89]:
arr.sum()

45

In [90]:
arr.std()

2.581988897471611

In [91]:
arr.var()

6.666666666666667

In [92]:
arr.mean()

5.0

In [97]:
arr = [4, 5, 2, 7, 1, 8, 3]
arr.sort()
arr

[1, 2, 3, 4, 5, 7, 8]

In [102]:
np.random.randint(69, 420, size = (4,4))

array([[333, 206, 242, 197],
       [259, 342, 244, 176],
       [337, 250, 220, 234],
       [277, 128, 143, 395]])

In [106]:
np.random.rand(4,4)

array([[0.14410163, 0.94602578, 0.29314777, 0.58930455],
       [0.00914405, 0.73629433, 0.41061119, 0.30587997],
       [0.19387232, 0.94269965, 0.71978587, 0.21349305],
       [0.37460951, 0.92345719, 0.83721873, 0.42351193]])

In [108]:
#concatenate
#extend
a = np.random.rand(2, 2)
b = np.random.rand(2,2)

print(a, b)
np.concatenate((a, b))

[[0.38827643 0.38191096]
 [0.91393364 0.73415218]] [[0.36677708 0.55902912]
 [0.14937534 0.95027267]]


array([[0.38827643, 0.38191096],
       [0.91393364, 0.73415218],
       [0.36677708, 0.55902912],
       [0.14937534, 0.95027267]])

In [115]:
'''
1 2    +     6 7
3 4          8 9

= 1 2 6 7
  3 4 8 9
'''

a = np.array([[1, 2], [3, 4]])
b = np.array([[6, 7], [8, 9]])

print(a, b)
c = np.hstack((a, b))
print(c)

[[1 2]
 [3 4]] [[6 7]
 [8 9]]
[[1 2 6 7]
 [3 4 8 9]]


In [118]:
#concatenate axis:

#defaults to zero
d = np.concatenate((a, b), axis = 0)
print(d)
e = np.concatenate((a, b), axis = 1)
print(e)

[[1 2]
 [3 4]
 [6 7]
 [8 9]]
[[1 2 6 7]
 [3 4 8 9]]


In [135]:
x = np.random.randint(1, 26, size = (5, 5))
print(x)
print(x[0][2])
print(x[0,2])

x[::]
#first row
x[0]
x[0, :]
#4th column
x[:, 3]

x[:, 4] = 0
print(x)

# change ones in the [1,3) rows and [2, 3) columns
x[1:3, 2:3] = -1
print(x)

#check if all in 2nd row are more than 90
print(x[1,:] >= 90)

#print last column
print(x[:, -1])
print(x[:, -1] >= 10)

[[18 17  2  9 17]
 [17 17 18  9 22]
 [15 22  3 20 14]
 [19 22 19 19  1]
 [ 8 20  1 16 17]]
2
2
[[18 17  2  9  0]
 [17 17 18  9  0]
 [15 22  3 20  0]
 [19 22 19 19  0]
 [ 8 20  1 16  0]]
[[18 17  2  9  0]
 [17 17 -1  9  0]
 [15 22 -1 20  0]
 [19 22 19 19  0]
 [ 8 20  1 16  0]]
[False False False False False]
[0 0 0 0 0]
[False False False False False]


In [145]:
y = np.zeros((5,5))



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
