<a href="https://colab.research.google.com/github/minerva12938/ai_notes_s22/blob/main/day_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

a = np.random.randint(10, 23, size = (4, 4))

print(a)
b = a
#successful "copy", more like pointer/shallow copy
print(b)

b[0][0] = -12121

#both get updated
print(a)
print(b)

#deep copy
c = a.copy()
print(c)

#this change only changes the value of c
c[0][0] = -100000
print(c)
print(a)

B = np.array([True, False, True, False])
print(B)
B == False

[[16 19 22 16]
 [16 16 16 20]
 [12 10 15 11]
 [11 13 16 15]]
[[16 19 22 16]
 [16 16 16 20]
 [12 10 15 11]
 [11 13 16 15]]
[[-12121     19     22     16]
 [    16     16     16     20]
 [    12     10     15     11]
 [    11     13     16     15]]
[[-12121     19     22     16]
 [    16     16     16     20]
 [    12     10     15     11]
 [    11     13     16     15]]
[[-12121     19     22     16]
 [    16     16     16     20]
 [    12     10     15     11]
 [    11     13     16     15]]
[[-100000      19      22      16]
 [     16      16      16      20]
 [     12      10      15      11]
 [     11      13      16      15]]
[[-12121     19     22     16]
 [    16     16     16     20]
 [    12     10     15     11]
 [    11     13     16     15]]
[ True False  True False]


array([False,  True, False,  True])

In [15]:
a = np.arange(10)
print(a)
a >= 5

#if a value is >= 5, set to -1
# a[a>=5] = -1
# print(a)

#if a value is < mean, set to -1
a[a < a.mean()] = -1
print(a)

[0 1 2 3 4 5 6 7 8 9]
[-1 -1 -1 -1 -1  5  6  7  8  9]


In [19]:
a = np.random.randint(10, 23, size = (4, 4))
b = np.random.randint(10, 23, size = (4, 4))

print(a)
print(b)

print()

#acts as matrix addition, dimensions must be same or and error will occur
print(a + b)

[[15 10 22 11]
 [16 16 21 19]
 [21 10 20 15]
 [21 22 11 18]]
[[18 17 13 21]
 [18 14 19 22]
 [13 18 11 13]
 [18 19 15 21]]

[[33 27 35 32]
 [34 30 40 41]
 [34 28 31 28]
 [39 41 26 39]]


In [25]:
y = np.random.randint(10, 23, size = (2, 2))
x = np.random.randint(10, 23, size = (2, 2))

print(x)
print(y)

print()

#acts as matrix multiplication, dimensions don't have to be same
print(y * x)
print()

#transposing - interchanging its rows into columns or columns into rows
print(x.T)
print(x.T)

[[21 10]
 [17 19]]
[[12 17]
 [14 20]]

[[252 170]
 [238 380]]

[[21 17]
 [10 19]]
[[21 17]
 [10 19]]


In [30]:
x = np.random.randint(10, 23, size = (2, 3))
y = np.random.randint(10, 23, size = (3, 2))

#just multiplies the  correspoinding values together
# print(x * y) -- doesn't work
# print(y * x)

#ways to do matrix multiplication

#dot product, for 2d arrays: works as a matrx 
print(x.dot(y))
print(y.dot(x))
print()

print(x @ y)
print(y @ x)
print()

print(np.matmul(x, y))
print(np.matmul(y, x))

[[720 698]
 [720 786]]
[[452 488 280]
 [486 624 340]
 [649 772 430]]

[[720 698]
 [720 786]]
[[452 488 280]
 [486 624 340]
 [649 772 430]]

[[720 698]
 [720 786]]
[[452 488 280]
 [486 624 340]
 [649 772 430]]


Python classes & objects

In [23]:
class calc():
  def __init__(self, a, b):
    #makes them global within the class
    self.a = a
    self.b = b

  def addd(self):
    return self.a + self.b

  def sub(self):
    return self.a - self.b
  
  def mult(self):
    return self.a * self.b

  def div(self):
    return self.a / self.b


In [8]:
a = int(input('a: '))
b = int(input('b: '))

a: 1
b: 2


In [13]:
initializing_class = calc(a, b)

In [16]:
initializing_class.sub()

-1

In [18]:
initializing_class.addd()

3

In [21]:
initializing_class.mult()

2

In [22]:
initializing_class.div()

0.5