<a href="https://colab.research.google.com/github/minerva12938/ai_notes_s22/blob/main/day_5_NumPy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# NumPy exercises


In [ ]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.21.6


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [ ]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [ ]:
np.ones((2, 2), int)

array([[1, 1],
       [1, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [ ]:
np.ones((3, 2), float)

array([[1., 1., 1.],
       [1., 1., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [ ]:
rows = 4
columns = 5
x = np.random.randint(1, 5, (rows, columns))
print(x)
print()

def same_shape(x):
  # or np.ones_like(x)
  return np.ones((x.shape), int)

print(same_shape(x))

[[2 1 2 3 1]
 [4 3 1 1 2]
 [3 1 2 3 3]
 [3 4 1 2 1]]

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [ ]:
print(x)
print()

def same_shape_zero(x):
  #or np.zeros_like(x)
  return np.zeros((x.shape), int)

print(same_shape_zero(x))

[[2 1 2 3 1]
 [4 3 1 1 2]
 [3 1 2 3 3]
 [3 4 1 2 1]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [ ]:
y= np.zeros((4, 4), int)
y[y == 0] = 5
print(y)

#or np.ones([4,4], dtype=np.int) * 5

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [ ]:
def same_shape_sevens(x):
  y = x.copy
  y = np.zeros((x.shape), int)
  y[y == 0] = 7
  #or np.ones([4,4], dtype=np.int) * 7
  return y

print(same_shape_sevens(x))

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [ ]:
z = np.identity(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [ ]:
q = np.random.randint(1, 11, 3)
print(q)

[6 1 1]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [ ]:
q = np.random.uniform(1, 11, size = (3, 3, 3))
# or np.random.randn(3, 3, 3)
print(q)

[[[1.20806003 2.43641952 6.21951065]
  [9.87118515 7.44639678 4.42934108]
  [4.38614038 8.97958486 3.53310294]]

 [[8.57767333 9.19199335 5.27290447]
  [5.30965356 6.09430223 8.26298918]
  [7.75674158 9.56995233 6.19475625]]

 [[9.6746614  8.16506063 7.97256924]
  [5.77675609 9.5302359  3.05936579]
  [4.49577455 2.59937184 7.05866263]]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [ ]:
x = list([1, 2, 3, 4, 5, 6])

def list_to_array(x):
  y = np.array(x)
  return y

print(list_to_array(x))

[1 2 3 4 5 6]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [ ]:
x = np.arange(1, 10)
print(x)
def copy_and_store (x):
  y = x.copy()
  return y

print(copy_and_store(x))

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

In [ ]:
x = np.arange(1, 11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

In [ ]:
x = np.arange(1, 11, 2)
print(x)

[1 3 5 7 9]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

In [ ]:
x = np.arange(10, 0, -1)
print(x)

[10  9  8  7  6  5  4  3  2  1]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [ ]:
x = np.arange(0, 9)
x.resize((3, 3))
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

In [ ]:
z = x.copy()
def return_size(z):
  return (z.size * z.itemsize)

print(return_size(z))

72


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [ ]:
x = np.arange(1, 9)
def first_elem(x):
  return x[0]
print(first_elem(x))

1


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

In [ ]:
def last_elem(x):
  return x[-1]
print(last_elem(x))

8


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

In [ ]:
def first_three(x):
  return x[:3]
print(first_three(x))

[1 2 3]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements

In [ ]:
def midd(x):
  return x[1:-2]
print(midd(x))

[2 3 4 5 6]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [ ]:
def rev(x):
  return x[::-1]
print(rev(x))

[8 7 6 5 4 3 2 1]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in an odd position

In [ ]:
#done assuming first element is @ 0, so at an even position
def odds(x):
  return x[1::2]
print(odds(x))

[2 4 6 8]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

In [ ]:
y = np.random.randint(1, 11, size = (3, 3))
print(y)
print()

def first_row(y):
  return y[0]

print(first_row(y))

[[5 2 9]
 [3 7 8]
 [3 7 9]]

[5 2 9]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [ ]:
def last_row(y):
  return y[-1]

print(last_row(y))

[3 7 9]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [ ]:
def first_elem_matrix(y):
  return y[0][0]

print(first_elem_matrix(y))

5


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [ ]:
def last_elem_matrix(y):
  return y[-1][-1]

print(last_elem_matrix(y))

9


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [ ]:
print(y)
print()
def first_two(y):
  return (y[0:2, 0:2])
print(first_two(y))

[[5 2 9]
 [3 7 8]
 [3 7 9]]

[[5 2]
 [3 7]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [ ]:
print(y)
print()
def last_two(y):
  return (y[-2:, -2:])
print(last_two(y))

[[5 2 9]
 [3 7 8]
 [3 7 9]]

[[7 8]
 [7 9]]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [ ]:
z = np.arange(1, 9)
print(z)
b = z.astype(float)
print(b)

[1 2 3 4 5 6 7 8]
[1. 2. 3. 4. 5. 6. 7. 8.]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [ ]:
y = z[::-1]
print(y)

[8 7 6 5 4 3 2 1]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [ ]:
def sort_it(x):
  x.sort()
  return x
print(sort_it(y))

[1 2 3 4 5 6 7 8]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, set the fifth element equal to 1

In [ ]:
def fifth_one(x):
  x[4] = 1
  return x
print(fifth_one(y))

[1 2 3 4 1 6 7 8]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

In [ ]:
r = np.array([50, 60, 80, 70])
def fifty_fourty(x):
  x[x == 50] = 40
  return x
print(fifty_fourty(r))

[40 60 80 70]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [ ]:
r = np.random.randint(1, 10, size = (3, 3))
print(r)
print()
def last_one(x):
  x[-1] = np.ones(shape = (1, len(x)))
  return x
print(last_one(r))

[[8 4 3]
 [5 2 4]
 [7 2 4]]

[[8 4 3]
 [5 2 4]
 [1 1 1]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [ ]:
r = np.random.randint(1, 10, size = (3, 3))
print(r)
print()
def last_zero(x):
  x[-1] = np.zeros(shape = (1, len(x)))
  return x
print(last_zero(r))

[[1 4 6]
 [1 7 4]
 [4 9 1]]

[[1 4 6]
 [1 7 4]
 [0 0 0]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [ ]:
r = np.random.randint(1, 10, size = (3, 3))
print(r)
print()
def add_five(x):
  return x + 5
print(add_five(r))

[[1 6 1]
 [7 8 3]
 [9 4 6]]

[[ 6 11  6]
 [12 13  8]
 [14  9 11]]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [ ]:
x = np.arange(-5, 10)
print(x)
x[x<0]

[-5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9]


array([-5, -4, -3, -2, -1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get the negative elements

In [ ]:
x = np.random.randint(-5, 6, 8)
print(x)
x[x<0]

[-4  0  0 -2 -1 -5  2 -5]


array([-4, -2, -1, -5, -5])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [ ]:
x = np.random.randint(-5, 15, 8)
print(x)
x[x>5]

[ 1  2 14  5  3 14  4  1]


array([14, 14])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [ ]:
x = np.random.randint(-5, 6, 8)
print(x)
print(x.mean())
x[x > x.mean()]

[ 1 -3 -3  0 -3 -4 -1  1]
-1.5


array([ 1,  0, -1,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [ ]:
x = np.random.randint(2, 11, 8)
print(x)
x[np.isin(x, [2, 10])]

[ 3  2  6  5  4 10  6 10]


array([ 2, 10, 10])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [ ]:
x = np.random.randint(-5, 5, 8)
print(x)
def no_zero(x):
  if (len(x[x == 0]) == 0):
    return True
  else: 
    return False

print(no_zero(x))

[ 4  3  4  2 -1 -2 -2 -1]
True


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is zero

In [ ]:
x = np.random.randint(-5, 5, 8)
print(x)
def one_zero(x):
  if (len(x[x == 0]) > 0):
    return True
  else: 
    return False

print(one_zero(x))

[ 3 -2 -5  0 -2  1  4  2]
True


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [ ]:
x = np.random.randint(-5, 5, 8)
print(x)
print(x.sum())

[ 4 -3 -1 -2  4  3  2  4]
11


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements

In [ ]:
x = np.random.randint(-5, 5, 8)
print(x)
print(x.mean())

[-4  0 -2 -4  0 -3  2 -5]
-2.0


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

In [ ]:
x = np.random.randint(-5, 5, size = (3, 4))
print(x)
print()
print(x.sum(axis = 0))

[[ 0  2 -5  1]
 [-1 -2 -3  3]
 [-4 -5 -2  1]]

[ -5  -5 -10   5]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its rows

In [ ]:
x = np.random.randint(-5, 5, size = (3, 4))
print(x)
print()
print(x.sum(axis = 1))

[[ 3 -1 -3  0]
 [-4 -3 -5 -2]
 [-3  4  3 -1]]

[ -1 -14   3]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [ ]:
x = np.random.randint(-5, 5, size = (3, 4))
print(x)
print(x.max())

[[-3  3 -1 -5]
 [ 0  0  2 -2]
 [-2 -3  0 -3]]
3


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)